# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_num', models.IntegerField()),
                ('profile_picture', models.ImageField(upload_to='media')),
            ],
        ),
    ]
